from __future__ import annotations

import shutil
import tempfile
from pathlib import Path

from docgen import render_all, write_all, check_generated_outputs
from product_validation.product_checks import validate_product_phases

from validation.tests.mutation_support import create_repo_fixture, deactivate_product_plans, mutate_json


FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures" / "product-validation"


def install_fixture(temp_repo: Path, source_name: str, dest_path: str) -> None:
    source = FIXTURE_DIR / source_name
    target = temp_repo / dest_path
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def accept_kernel(temp_repo: Path) -> None:
    mutate_json(
        temp_repo / "product/specs/product/manifest.json",
        lambda manifest: manifest["product_specifications"][0].__setitem__("status", "accepted") or manifest,
    )
    mutate_json(
        temp_repo / "product/specs/product/level-0/kernel.json",
        lambda spec: (
            spec.__setitem__("status", "accepted"),
            spec.__setitem__("derived_artifacts", [{"type": "markdown", "path": "product/derived/specs/product/kernel.md"}]),
            spec.__setitem__(
                "correspondence",
                {
                    "implementations": [
                        {"id": "impl.kernel", "paths": ["product/src/kernel.py"], "requirements": ["KERNEL-001"]}
                    ],
                    "tests": [
                        {"id": "test.kernel", "paths": ["product/tests/test_kernel.py"], "requirements": ["KERNEL-001"]}
                    ],
                    "conformance": [
                        {
                            "requirement_id": "KERNEL-001",
                            "implementation_ids": ["impl.kernel"],
                            "test_ids": ["test.kernel"],
                            "status": "covered",
                        }
                    ],
                },
            ),
            spec,
        )[-1],
    )


def snapshot_generated_docs(repo_root: Path) -> dict[str, str]:
    derived_root = repo_root / "product/derived/specs/product"
    return {
        path.relative_to(repo_root).as_posix(): path.read_text()
        for path in sorted(derived_root.glob("*.md"))
    }


def run_product_generation_tests(repo_root: Path) -> None:
    with tempfile.TemporaryDirectory(prefix="repo-spec-validation-") as temp_root_name:
        temp_root = Path(temp_root_name)

        temp_repo = create_repo_fixture(repo_root, temp_root, 0)
        install_fixture(temp_repo, "manifest-valid-four.json", "product/specs/product/manifest.json")
        install_fixture(temp_repo, "level-0-candidate.json", "product/specs/product/level-0/kernel.json")
        install_fixture(temp_repo, "level-1-accepted.json", "product/specs/product/level-1/primitive.json")
        install_fixture(temp_repo, "level-2-accepted.json", "product/specs/product/level-2/component.json")
        install_fixture(temp_repo, "level-3-accepted.json", "product/specs/product/level-3/orchestration.json")
        accept_kernel(temp_repo)
        deactivate_product_plans(temp_repo)

        render_paths = [path for path in render_all(temp_repo) if path.startswith("product/derived/specs/product/")]
        assert render_paths == [
            "product/derived/specs/product/kernel.md",
            "product/derived/specs/product/primitive.md",
            "product/derived/specs/product/component.md",
            "product/derived/specs/product/orchestration.md",
        ]

        write_all(temp_repo)
        check_generated_outputs(temp_repo)
        first_pass = snapshot_generated_docs(temp_repo)

        kernel_doc = temp_repo / "product/derived/specs/product/kernel.md"
        primitive_doc = temp_repo / "product/derived/specs/product/primitive.md"
        component_doc = temp_repo / "product/derived/specs/product/component.md"
        orchestration_doc = temp_repo / "product/derived/specs/product/orchestration.md"

        assert "Generated by `product/scripts/generate-docs` from `product/specs/product/level-0/kernel.json`." in kernel_doc.read_text()
        assert "## Kernel" in kernel_doc.read_text()
        assert "## Correspondence" in kernel_doc.read_text()
        assert "impl.kernel" in kernel_doc.read_text()
        assert "- Foundations:" in kernel_doc.read_text()
        assert "- `terminology`" in kernel_doc.read_text()

        assert "Generated by `product/scripts/generate-docs` from `product/specs/product/level-1/primitive.json`." in primitive_doc.read_text()
        assert "## Correspondence" in primitive_doc.read_text()
        assert "impl.primitive" in primitive_doc.read_text()
        assert "## Primitives" in primitive_doc.read_text()
        assert "- Concepts:" in primitive_doc.read_text()

        assert "Generated by `product/scripts/generate-docs` from `product/specs/product/level-2/component.json`." in component_doc.read_text()
        assert "## Correspondence" in component_doc.read_text()
        assert "impl.component" in component_doc.read_text()
        assert "## Components" in component_doc.read_text()
        assert "- Contracts:" in component_doc.read_text()

        assert "Generated by `product/scripts/generate-docs` from `product/specs/product/level-3/orchestration.json`." in orchestration_doc.read_text()
        assert "## Correspondence" in orchestration_doc.read_text()
        assert "impl.orchestration" in orchestration_doc.read_text()
        assert "## Orchestrations" in orchestration_doc.read_text()
        assert "- Workflows:" in orchestration_doc.read_text()

        write_all(temp_repo)
        check_generated_outputs(temp_repo)
        second_pass = snapshot_generated_docs(temp_repo)
        assert first_pass == second_pass

        validate_product_phases(temp_repo, ('product generated-document freshness',))

    print("ok: product generation tests")
