#!/usr/bin/env python3

"""Deterministic Markdown generation for repo-spec JSON artifacts."""

from __future__ import annotations

import json
import sys
from pathlib import Path

GENERATOR_NAME = "scripts/generate-docs"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def load_specs(repo_root: Path) -> dict[str, dict]:
    return {
        "repo.manifest": load_json(repo_root / "specs/repo/manifest.json"),
        "repo.governing-issue": load_json(repo_root / "specs/repo/governing-issue.json"),
        "repo.repository-structure": load_json(repo_root / "specs/repo/repository-structure.json"),
        "repo.development-workflow": load_json(repo_root / "specs/repo/development-workflow.json"),
        "repo.validation": load_json(repo_root / "specs/repo/validation.json"),
    }


def header(title: str, source_path: str) -> str:
    return "\n".join(
        [
            f"# {title}",
            "",
            "## Status",
            "",
            f"Generated by `{GENERATOR_NAME}` from `{source_path}`.",
            "",
            "This document is non-normative.",
            "Do not edit directly.",
            "",
            "## Authoritative source",
            "",
            f"`{source_path}`",
            "",
            "## Generator",
            "",
            f"`{GENERATOR_NAME}`",
        ]
    )


def render_manifest(spec: dict) -> str:
    lines = [
        header("Repository Spec Manifest", "specs/repo/manifest.json"),
        "## Purpose",
        "",
        spec["purpose"],
        "",
        "## Authoritative specs",
        "",
    ]
    for entry in spec["authoritative_specs"]:
        lines.append(f"- `{entry['spec_id']}` -> `{entry['path']}`")
    return "\n".join(lines) + "\n"


def render_governing_issue(spec: dict) -> str:
    lines = [
        header("Governing Issue Contract", "specs/repo/governing-issue.json"),
        "## Canonical contract",
        "",
        "Use one governing issue for each bounded governed change. The canonical contract is repository-spec authority; Markdown and GitHub forms are adapters only.",
        "",
        "## Required fields",
        "",
    ]
    lines.extend(f"- {field}" for field in [
        "Change type",
        "Problem statement",
        "Intended outcome",
        "Governing specifications",
        "Accepted default-branch base",
        "Intended branch",
        "In-scope behavior and paths",
        "Explicit exclusions",
        "Dependencies and predecessor evidence",
        "Ordered patch plan",
        "Validation plan",
        "Acceptance criteria",
        "Completion gate",
        "Open decisions or authority conflicts",
        "Successor work explicitly not authorized",
    ])
    lines.extend(
        [
            "",
            "## Required-field rules",
            "",
            "- Every required field shall contain substantive content.",
            "- Empty placeholders do not satisfy required fields.",
            "- Material scope changes must be recorded in the governing issue.",
            "- The issue must exist before the implementation branch is created.",
            "- The issue may close only after its completion gate is satisfied.",
            "- Completion does not authorize unrelated successor work.",
            "",
            "## Optional fields",
            "",
            "- Related links",
            "- Notes",
            "- Risk callouts",
            "- Session recovery context",
            "",
            "## Adapter guidance",
            "",
            "- The Markdown projection is the human-readable generic form.",
            "- The GitHub Issue Form is the platform-specific form.",
            "- Neither adapter may override the canonical repository specification.",
        ]
    )
    return "\n".join(lines) + "\n"


def render_structure(spec: dict) -> str:
    return (
        header("Repository Structure", "specs/repo/repository-structure.json")
        + "\n## Purpose\n\n"
        + f"{spec['normative_requirements'][0]['text']}\n\n"
        + "## Reference context\n\n"
        + "- `repo.manifest`\n"
        + "- `docs/plans/00-bootstrap-plan.md`\n"
    )


def render_workflow(spec: dict) -> str:
    return (
        header("Development Workflow", "specs/repo/development-workflow.json")
        + "\n## Purpose\n\n"
        + f"{spec['purpose']}\n\n"
        + "## Normative requirements\n\n"
        + "\n".join(f"- {req['id']}: {req['text']}" for req in spec["normative_requirements"])
        + "\n\n"
        + "## Reference context\n\n"
        + "- `AGENTS.md`\n"
        + "- `repo.manifest`\n"
        + "- `repo.repository-structure`\n"
        + "- `docs/overview/product-overview/03-git-and-change-workflow.md`\n"
        + "- `docs/overview/product-overview/04-human-ai-continuity.md`\n"
    )


def render_validation(spec: dict) -> str:
    return (
        header("Validation", "specs/repo/validation.json")
        + "\n## Purpose\n\n"
        + f"{spec['normative_requirements'][0]['text']}\n\n"
        + "## Closed checks\n\n"
        + "1. Conformance to the repository's JSON Schemas\n"
        + "2. Manifest completeness\n"
        + "3. Unique specification IDs\n"
        + "4. Resolvable references\n"
        + "5. Acyclic dependencies\n"
        + "6. Generated-document freshness\n"
        + "7. Clean failure behavior\n\n"
        + "## Boundaries\n\n"
        + "- shell-only\n"
        + "- no external dependencies\n"
        + "- no formatting checks\n"
        + "- no prose checks\n"
        + "- no Git workflow checks\n"
        + "- no hosting-platform checks\n"
        + "- no product-spec checks\n"
        + "- no source-code checks\n"
    )


def render_all(repo_root: Path) -> dict[str, str]:
    specs = load_specs(repo_root)
    return {
        "repo.manifest": render_manifest(specs["repo.manifest"]),
        "repo.governing-issue": render_governing_issue(specs["repo.governing-issue"]),
        "repo.repository-structure": render_structure(specs["repo.repository-structure"]),
        "repo.development-workflow": render_workflow(specs["repo.development-workflow"]),
        "repo.validation": render_validation(specs["repo.validation"]),
    }


def write_all(repo_root: Path) -> None:
    rendered = render_all(repo_root)
    targets = {
        "repo.manifest": repo_root / "derived/specs/repo/manifest.md",
        "repo.governing-issue": repo_root / "derived/specs/repo/governing-issue.md",
        "repo.repository-structure": repo_root / "derived/specs/repo/repository-structure.md",
        "repo.development-workflow": repo_root / "derived/specs/repo/development-workflow.md",
        "repo.validation": repo_root / "derived/specs/repo/validation.md",
    }
    for spec_id, content in rendered.items():
        path = targets[spec_id]
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def main(argv: list[str]) -> int:
    repo_root = Path(argv[1]).resolve() if len(argv) > 1 else Path.cwd().resolve()
    mode = argv[2] if len(argv) > 2 else "--write"
    rendered = render_all(repo_root)
    targets = {
        "repo.manifest": repo_root / "derived/specs/repo/manifest.md",
        "repo.governing-issue": repo_root / "derived/specs/repo/governing-issue.md",
        "repo.repository-structure": repo_root / "derived/specs/repo/repository-structure.md",
        "repo.development-workflow": repo_root / "derived/specs/repo/development-workflow.md",
        "repo.validation": repo_root / "derived/specs/repo/validation.md",
    }

    if mode == "--write":
        for spec_id, content in rendered.items():
            path = targets[spec_id]
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        return 0

    if mode == "--check":
        for spec_id, content in rendered.items():
            path = targets[spec_id]
            if not path.exists() or path.read_text() != content:
                print(f"stale generated document: {path.relative_to(repo_root)}", file=sys.stderr)
                return 1
        return 0

    print(f"unknown mode: {mode}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
