#!/usr/bin/env python3

"""Deterministic Markdown generation for repo-spec JSON artifacts."""

from __future__ import annotations

import json
import sys
from pathlib import Path

GENERATOR_NAME = "scripts/generate-docs"


def load_json(path: Path) -> dict:
    return json.loads(path.read_text())


def resolve_repo_path(repo_root: Path, value: str) -> Path:
    if not value:
        raise ValueError(f"invalid repository-relative path: {value}")
    if value.startswith("/") or value.startswith("./") or "/./" in value or value.endswith("/.") or "\\" in value or "//" in value:
        raise ValueError(f"invalid repository-relative path: {value}")
    relative = Path(value)
    if any(part in {".", ".."} for part in relative.parts):
        raise ValueError(f"invalid repository-relative path: {value}")
    resolved = (repo_root / relative).resolve()
    try:
        resolved.relative_to(repo_root.resolve())
    except ValueError as exc:
        raise ValueError(f"invalid repository-relative path: {value}") from exc
    return resolved


def load_manifest(repo_root: Path) -> dict:
    return load_json(repo_root / "specs/repo/manifest.json")


def load_specs(repo_root: Path) -> tuple[dict, dict[str, dict], dict[str, str], list[str]]:
    manifest = load_manifest(repo_root)
    actual_paths = sorted(path.relative_to(repo_root).as_posix() for path in (repo_root / "specs/repo").glob("*.json"))
    manifest_paths = [entry["path"] for entry in manifest["authoritative_specs"]]
    if len(manifest_paths) != len(set(manifest_paths)):
        raise ValueError("manifest completeness failed")
    if set(actual_paths) != set(manifest_paths):
        raise ValueError("manifest completeness failed")

    specs = {"repo.manifest": manifest}
    paths = {"repo.manifest": "specs/repo/manifest.json"}
    path_to_spec_id = {entry["path"]: entry["spec_id"] for entry in manifest["authoritative_specs"]}
    for path in actual_paths:
        expected_spec_id = path_to_spec_id[path]
        if path == "specs/repo/manifest.json":
            if manifest["spec_id"] != expected_spec_id:
                raise ValueError(f"manifest entry {expected_spec_id} does not match {path}")
            paths[expected_spec_id] = path
            continue
        spec = load_json(repo_root / path)
        spec_id = spec["spec_id"]
        if spec_id != expected_spec_id:
            raise ValueError(f"manifest entry {expected_spec_id} does not match {path}")
        if spec_id in specs:
            raise ValueError(f"duplicate authoritative spec_id: {spec_id}")
        specs[spec_id] = spec
        paths[spec_id] = path
    return manifest, specs, paths, actual_paths


def header(title: str, source_path: str) -> str:
    return "\n".join(
        [
            f"# {title}",
            "",
            "## Status",
            "",
            f"Generated by `{GENERATOR_NAME}` from `{source_path}`.",
            "",
            "This document is non-normative.",
            "Do not edit directly.",
            "",
            "## Authoritative source",
            "",
            f"`{source_path}`",
            "",
            "## Generator",
            "",
            f"`{GENERATOR_NAME}`",
        ]
    )


def render_list_section(title: str, items: list[str]) -> list[str]:
    lines = [f"## {title}", ""]
    lines.extend(items or ["- None"])
    lines.append("")
    return lines


def render_requirements(spec: dict) -> list[str]:
    return [f"- `{req['id']}`: {req['text']}" for req in spec["normative_requirements"]]


def render_dependencies(spec: dict) -> list[str]:
    return [f"- `{dep['spec_id']}`" for dep in spec.get("dependencies", [])]


def render_references(spec: dict) -> list[str]:
    items = []
    for ref in spec.get("references", []):
        if ref["type"] == "specification":
            kind = ref.get("kind", "normative")
            if kind == "historical":
                items.append(f"- historical specification: `{ref['spec_id']}`")
            else:
                items.append(f"- specification: `{ref['spec_id']}`")
        else:
            items.append(f"- artifact: `{ref['path']}`")
    return items


def render_derived_artifacts(spec: dict) -> list[str]:
    items = []
    for artifact in spec.get("derived_artifacts", []):
        line = f"- `{artifact['type']}`: `{artifact['path']}`"
        if "renderer" in artifact:
            line += f" (renderer: `{artifact['renderer']}`)"
        items.append(line)
    return items


def render_field_sections(fields: list[dict]) -> list[str]:
    lines = ["## Canonical fields", ""]
    for field in fields:
        lines.extend(
            [
                f"### {field['label']}",
                "",
                f"- Field ID: `{field['id']}`",
                f"- Required: {'yes' if field['required'] else 'no'}",
                f"- Input type: `{field['input_type']}`",
                "",
                field["description"],
                "",
                "Placeholder:",
            ]
        )
        for line in field["placeholder"].splitlines() or [""]:
            lines.append(f"> {line}" if line else ">")
        lines.append("")
    return lines


def render_issue_form(spec: dict) -> str:
    lines = [
        "name: Governing issue",
        "description: Create a standardized governing issue for bounded governed work.",
        'title: "[governed] "',
        "labels:",
        "  - governed-work",
        "body:",
        "  - type: markdown",
        "    attributes:",
        "      value: |",
        "        Use this form to create the canonical governing issue. Required fields must be filled with substantive content; placeholders do not count as complete.",
    ]
    for field in spec["issue_fields"]:
        lines.extend(
            [
                f"  - type: {field['input_type']}",
                f"    id: {field['id']}",
                "    attributes:",
                f"      label: {json.dumps(field['label'])}",
                f"      description: {json.dumps(field['description'])}",
                f"      placeholder: {json.dumps(field['placeholder'])}",
                "    validations:",
                f"      required: {'true' if field['required'] else 'false'}",
            ]
        )
    return "\n".join(lines) + "\n"


def render_governing_issue_example(spec: dict) -> str:
    lines = ["# Governing Issue Example", ""]
    lines.extend(render_field_sections(spec["issue_fields"]))
    return "\n".join(lines)


def render_review_template(spec: dict) -> str:
    lines = [
        "## Development",
        "",
        "Use the PR's GitHub `Development` section to link the governing issue.",
        "Do not use automatic close syntax unless the governing issue explicitly permits closure on merge.",
        "When closure on merge is authorized, end the PR body with `Closes #<issue-number>`.",
        "",
    ]
    for field in spec["review_fields"]:
        lines.extend(
            [
                f"## {field['label']}",
                "",
                field["description"],
                "",
            ]
        )
        if field["id"] == "acceptance_checklist":
            for line in field["placeholder"].splitlines():
                lines.append(line)
        else:
            lines.append(f"`{field['id']}` ({'required' if field['required'] else 'optional'}, `{field['input_type']}`)")
            lines.append("")
            lines.append(field["placeholder"])
        lines.append("")
    return "\n".join(lines)


def render_authoritative_specs(spec: dict) -> list[str]:
    return [f"- `{entry['spec_id']}` -> `{entry['path']}`" for entry in spec.get("authoritative_specs", [])]


def render_lineage(spec: dict) -> list[str]:
    lines: list[str] = []
    if spec.get("supersedes"):
        lines.append("## Supersedes")
        lines.append("")
        lines.extend([f"- `{spec_id}`" for spec_id in spec["supersedes"]])
        lines.append("")
    if spec.get("superseded_by"):
        lines.append("## Superseded By")
        lines.append("")
        lines.extend([f"- `{spec_id}`" for spec_id in spec["superseded_by"]])
        lines.append("")
    return lines


def render_spec_projection(title: str, source_path: str, spec: dict, include_authoritative_specs: bool = False) -> str:
    lines = [header(title, source_path), "## Purpose", "", spec["purpose"], ""]
    if "issue_fields" in spec:
        lines.extend(render_field_sections(spec["issue_fields"]))
    elif "review_fields" in spec:
        lines.extend(render_field_sections(spec["review_fields"]))
    lines.extend(render_lineage(spec))
    if include_authoritative_specs:
        lines.extend(render_list_section("Authoritative specs", render_authoritative_specs(spec)))
    lines.extend(render_list_section("Normative requirements", render_requirements(spec)))
    lines.extend(render_list_section("Dependencies", render_dependencies(spec)))
    lines.extend(render_list_section("References", render_references(spec)))
    lines.extend(render_list_section("Derived artifacts", render_derived_artifacts(spec)))
    return "\n".join(lines) + "\n"


def render_manifest(spec: dict) -> str:
    return render_spec_projection("Repository Spec Manifest", "specs/repo/manifest.json", spec, include_authoritative_specs=True)


def render_governing_issue(spec: dict) -> str:
    return render_spec_projection("Governing Issue Contract", "specs/repo/governing-issue.json", spec)


def render_review_proposal(spec: dict) -> str:
    return render_spec_projection("Review Proposal Contract", "specs/repo/review-proposal.json", spec)


def render_structure(spec: dict) -> str:
    return render_spec_projection("Repository Structure", "specs/repo/repository-structure.json", spec)


def render_workflow(spec: dict) -> str:
    return render_spec_projection("Development Workflow", "specs/repo/development-workflow.json", spec)


def render_validation(spec: dict) -> str:
    return render_spec_projection("Validation", "specs/repo/validation.json", spec)


SPECIAL_RENDERERS = {
    "issue-form": render_issue_form,
    "governing-issue-example": render_governing_issue_example,
    "review-template": render_review_template,
}


def declared_derived_artifact_paths(specs: dict[str, dict]) -> set[str]:
    paths: list[str] = []
    for spec in specs.values():
        for artifact in spec.get("derived_artifacts", []):
            if artifact.get("type") not in {"markdown", "yaml"}:
                raise ValueError(f"unsupported derived artifact type: {artifact.get('type')}")
            paths.append(artifact["path"])
    if len(paths) != len(set(paths)):
        raise ValueError("duplicate derived artifact paths failed")
    return set(paths)


def actual_derived_markdown_paths(repo_root: Path) -> set[str]:
    derived_root = repo_root / "derived/specs/repo"
    if not derived_root.exists():
        return set()
    return {
        path.relative_to(repo_root).as_posix()
        for path in derived_root.glob("*.md")
        if path.is_file()
    }


def check_orphaned_derived_markdown(repo_root: Path, expected_paths: set[str], strict: bool) -> None:
    actual_paths = actual_derived_markdown_paths(repo_root)
    missing = sorted(expected_paths - actual_paths)
    extra = sorted(actual_paths - expected_paths)
    if strict:
        if missing or extra:
            parts: list[str] = []
            if missing:
                parts.append(f"missing derived markdown: {', '.join(missing)}")
            if extra:
                parts.append(f"orphaned derived markdown: {', '.join(extra)}")
            raise ValueError("; ".join(parts))
        return
    if extra:
        raise ValueError(f"orphaned derived markdown: {', '.join(extra)}")


def render_all(repo_root: Path) -> dict[str, str]:
    _manifest, specs, paths, _actual_paths = load_specs(repo_root)
    rendered: dict[str, str] = {}
    for spec_id, spec in specs.items():
        source_path = paths[spec_id]
        for artifact in spec.get("derived_artifacts", []):
            resolve_repo_path(repo_root, artifact["path"])
            renderer_id = artifact.get("renderer")
            if renderer_id is None:
                if artifact["type"] != "markdown":
                    raise ValueError(f"unsupported derived artifact type without renderer: {artifact['type']}")
                rendered[artifact["path"]] = render_spec_projection(spec["title"], source_path, spec, include_authoritative_specs=(spec_id == "repo.manifest"))
                continue
            renderer = SPECIAL_RENDERERS.get(renderer_id)
            if renderer is None:
                raise ValueError(f"unsupported renderer: {renderer_id}")
            rendered[artifact["path"]] = renderer(spec)
    declared_paths = declared_derived_artifact_paths(specs)
    if set(rendered) != declared_paths:
        raise ValueError("declared derived-artifacts do not match generated outputs")
    return rendered


def write_all(repo_root: Path) -> None:
    rendered = render_all(repo_root)
    for relative_path, content in rendered.items():
        path = resolve_repo_path(repo_root, relative_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def main(argv: list[str]) -> int:
    repo_root = Path(argv[1]).resolve() if len(argv) > 1 else Path.cwd().resolve()
    mode = argv[2] if len(argv) > 2 else "--write"
    rendered = render_all(repo_root)
    expected_markdown_paths = {path for path in rendered if path.startswith("derived/specs/repo/") and path.endswith(".md")}

    if mode == "--write":
        check_orphaned_derived_markdown(repo_root, expected_markdown_paths, strict=False)
        for relative_path, content in rendered.items():
            path = resolve_repo_path(repo_root, relative_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        return 0

    if mode == "--check":
        check_orphaned_derived_markdown(repo_root, expected_markdown_paths, strict=True)
        for relative_path, content in rendered.items():
            path = resolve_repo_path(repo_root, relative_path)
            if not path.exists() or path.read_text() != content:
                print(f"stale generated document: {path.relative_to(repo_root)}", file=sys.stderr)
                return 1
        return 0

    print(f"unknown mode: {mode}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
