#!/usr/bin/env python3

"""Deterministic Markdown generation for product-spec JSON artifacts."""

from __future__ import annotations

import json
import sys
from pathlib import Path

class RepositoryError(Exception):
    pass


def load_json(path: Path) -> object:
    try:
        return json.loads(path.read_text())
    except OSError as exc:
        raise RepositoryError(f"missing required file: {path}") from exc
    except json.JSONDecodeError as exc:
        raise RepositoryError(f"invalid JSON: {path}: {exc.msg}") from exc


def resolve_repo_path(repo_root: Path, value: str) -> Path:
    if not value:
        raise RepositoryError(f"invalid repository-relative path: {value}")
    if value.startswith("/") or value.startswith("./") or "/./" in value or value.endswith("/.") or "\\" in value or "//" in value:
        raise RepositoryError(f"invalid repository-relative path: {value}")
    relative = Path(value)
    if any(part in {".", ".."} for part in relative.parts):
        raise RepositoryError(f"invalid repository-relative path: {value}")
    resolved = (repo_root / relative).resolve()
    try:
        resolved.relative_to(repo_root.resolve())
    except ValueError as exc:
        raise RepositoryError(f"invalid repository-relative path: {value}") from exc
    return resolved


def index_product_manifest_paths(manifest: dict) -> tuple[dict[str, str], dict[str, str]]:
    path_to_spec_id: dict[str, str] = {}
    spec_id_to_path: dict[str, str] = {}
    for entry in manifest["product_specifications"]:
        spec_id = entry["spec_id"]
        path = entry["path"]
        if path in path_to_spec_id:
            raise RepositoryError(f"duplicate product specification path: {path}")
        if spec_id in spec_id_to_path:
            raise RepositoryError(f"duplicate product specification id: {spec_id}")
        path_to_spec_id[path] = spec_id
        spec_id_to_path[spec_id] = path
    return path_to_spec_id, spec_id_to_path


def load_product_specs(repo_root: Path) -> tuple[dict, dict[str, dict], dict[str, str], list[str]]:
    manifest_path = repo_root / "product/specs/product/manifest.json"
    if not manifest_path.exists():
        return {}, {}, {}, []
    manifest = load_json(manifest_path)
    if not isinstance(manifest, dict):
        raise RepositoryError("product manifest must be a JSON object")
    actual_paths = sorted(
        path.relative_to(repo_root).as_posix()
        for path in (repo_root / "product/specs/product").rglob("*.json")
        if path.is_file() and path.relative_to(repo_root).as_posix() != "product/specs/product/manifest.json"
    )
    manifest_paths = [entry["path"] for entry in manifest["product_specifications"]]
    if len(manifest_paths) != len(set(manifest_paths)):
        raise RepositoryError("product manifest completeness failed")
    if set(actual_paths) != set(manifest_paths):
        raise RepositoryError("product manifest completeness failed")
    path_to_spec_id, spec_id_to_path = index_product_manifest_paths(manifest)
    specs: dict[str, dict] = {}
    paths: dict[str, str] = {}
    for path in actual_paths:
        expected_spec_id = path_to_spec_id[path]
        spec = load_json(repo_root / path)
        if not isinstance(spec, dict):
            raise RepositoryError(f"product specification must be a JSON object: {path}")
        spec_id = spec["spec_id"]
        if spec_id != expected_spec_id:
            raise RepositoryError(f"product manifest entry {expected_spec_id} does not match {path}")
        if spec_id in specs:
            raise RepositoryError(f"duplicate product specification id: {spec_id}")
        specs[spec_id] = spec
        paths[spec_id] = path
    if set(paths) != set(spec_id_to_path):
        raise RepositoryError("product manifest completeness failed")
    return manifest, specs, paths, actual_paths


def declared_derived_artifact_paths(specs: dict[str, dict]) -> set[str]:
    paths: list[str] = []
    for spec in specs.values():
        for artifact in spec.get("derived_artifacts", []):
            if artifact.get("type") not in {"markdown", "yaml"}:
                raise RepositoryError(f"unsupported derived artifact type: {artifact.get('type')}")
            paths.append(artifact["path"])
    if len(paths) != len(set(paths)):
        raise RepositoryError("duplicate derived artifact paths failed")
    return set(paths)


GENERATOR_NAME = "product/scripts/generate-docs"

COMMON_SPEC_KEYS = {
    "spec_id",
    "title",
    "purpose",
    "status",
    "schema_version",
    "level",
    "normative_requirements",
    "dependencies",
    "references",
    "supersedes",
    "superseded_by",
    "derived_artifacts",
    "correspondence",
    "artifact_classes",
    "profiles",
    "issue_fields",
    "review_fields",
    "authoritative_specs",
}


def header(title: str, source_path: str) -> str:
    return "\n".join(
        [
            f"# {title}",
            "",
            "## Status",
            "",
            f"Generated by `{GENERATOR_NAME}` from `{source_path}`.",
            "",
            "This document is non-normative.",
            "Do not edit directly.",
            "",
            "## Authoritative source",
            "",
            f"`{source_path}`",
            "",
            "## Generator",
            "",
            f"`{GENERATOR_NAME}`",
        ]
    )


def render_list_section(title: str, items: list[str]) -> list[str]:
    lines = [f"## {title}", ""]
    lines.extend(items or ["- None"])
    lines.append("")
    return lines


def render_requirements(spec: dict) -> list[str]:
    return [f"- `{req['id']}`: {req['text']}" for req in spec["normative_requirements"]]


def render_dependencies(spec: dict) -> list[str]:
    return [f"- `{dep['spec_id']}`" for dep in spec.get("dependencies", [])]


def render_references(spec: dict) -> list[str]:
    items = []
    for ref in spec.get("references", []):
        if ref["type"] == "specification":
            kind = ref.get("kind", "normative")
            if kind == "historical":
                items.append(f"- historical specification: `{ref['spec_id']}`")
            else:
                items.append(f"- specification: `{ref['spec_id']}`")
        else:
            items.append(f"- artifact: `{ref['path']}`")
    return items


def render_derived_artifacts(spec: dict) -> list[str]:
    items = []
    for artifact in spec.get("derived_artifacts", []):
        line = f"- `{artifact['type']}`: `{artifact['path']}`"
        if "renderer" in artifact:
            line += f" (renderer: `{artifact['renderer']}`)"
        items.append(line)
    return items


def render_correspondence_collection(title: str, records: list[dict], identifier_field: str, fields: list[str]) -> list[str]:
    lines = [f"### {title}", ""]
    if not records:
        lines.extend(["- None", ""])
        return lines

    for record in sorted(records, key=lambda item: item[identifier_field]):
        lines.append(f"- {render_scalar(record[identifier_field])}")
        for field in fields:
            if field == identifier_field or field not in record:
                continue
            value = record[field]
            label = field.replace("_", " ").title()
            if isinstance(value, list):
                lines.append(f"  - {label}:")
                if value:
                    lines.extend([f"    - {render_scalar(item)}" for item in value])
                else:
                    lines.append("    - None")
            else:
                lines.append(f"  - {label}: {render_scalar(value)}")
        lines.append("")
    return lines


def render_correspondence(spec: dict) -> list[str]:
    correspondence = spec["correspondence"]
    lines = ["## Correspondence", ""]
    lines.extend(render_correspondence_collection("Implementations", correspondence["implementations"], "id", ["id", "paths", "requirements"]))
    lines.extend(render_correspondence_collection("Tests", correspondence["tests"], "id", ["id", "paths", "requirements"]))
    lines.extend(
        render_correspondence_collection(
            "Conformance",
            correspondence["conformance"],
            "requirement_id",
            ["requirement_id", "implementation_ids", "test_ids", "status", "rationale"],
        )
    )
    return lines


def render_scalar(value: object) -> str:
    text = str(value).replace("`", "\\`")
    return f"`{text}`"


def render_nested_value(value: object, indent: int = 0) -> list[str]:
    prefix = "  " * indent
    if isinstance(value, dict):
        lines: list[str] = []
        if not value:
            return [f"{prefix}- None"]
        for key in sorted(value):
            child = value[key]
            label = key.replace("_", " ").title()
            if isinstance(child, (dict, list)):
                lines.append(f"{prefix}- {label}:")
                lines.extend(render_nested_value(child, indent + 1))
            else:
                lines.append(f"{prefix}- {label}: {render_scalar(child)}")
        return lines
    if isinstance(value, list):
        if not value:
            return [f"{prefix}- None"]
        lines: list[str] = []
        for item in value:
            if isinstance(item, (dict, list)):
                lines.extend(render_nested_value(item, indent))
            else:
                lines.append(f"{prefix}- {render_scalar(item)}")
        return lines
    return [f"{prefix}- {render_scalar(value)}"]


def render_extra_sections(spec: dict) -> list[str]:
    lines: list[str] = []
    extra_keys = [key for key in sorted(spec) if key not in COMMON_SPEC_KEYS]
    for key in extra_keys:
        lines.extend([f"## {key.replace('_', ' ').title()}", ""])
        lines.extend(render_nested_value(spec[key]))
        lines.append("")
    return lines


def render_artifact_classes(spec: dict) -> list[str]:
    lines = ["## Artifact classes", ""]
    for artifact in spec["artifact_classes"]:
        lines.extend(
            [
                f"### {artifact['label']}",
                "",
                f"- Identifier: `{artifact['identifier']}`",
                f"- Role: `{artifact['role']}`",
                f"- Authority category: `{artifact['authority_category']}`",
                f"- Authority source: {artifact['authority_source']}",
                f"- Source of truth rule: {artifact['source_of_truth_rule']}",
                f"- Mutability: {artifact['mutability']}",
                f"- Generation mode: `{artifact['generation_mode']}`",
                f"- Validation ownership: `{artifact['validation_ownership']}`",
                f"- Portability category: `{artifact['portability_category']}`",
                f"- Manifest participation: `{artifact['manifest_participation']}`",
            ]
        )
        if artifact.get("source_artifacts"):
            lines.extend(["", "- Source artifacts:"])
            lines.extend([f"  - `{source}`" for source in artifact["source_artifacts"]])
        lines.append("")
    return lines


def render_profiles(spec: dict) -> list[str]:
    lines = ["## Profiles", ""]
    for profile in spec["profiles"]:
        lines.extend(
            [
                f"### {profile['label']}",
                "",
                f"- Identifier: `{profile['identifier']}`",
                f"- Source root: `{profile['source_root']}`",
                f"- Installed adapter root: `{profile['installed_adapter_root']}`",
                f"- Authority boundary: `{profile['authority_boundary']}`",
                f"- Adapter generation policy: `{profile['adapter_generation_policy']}`",
            ]
        )
        lines.extend(["", "- Artifact inventory:"])
        for item in profile["artifact_inventory"]:
            lines.append(
                f"  - `{item['path']}` -> `{item['classification']}` / `{item['authority_category']}` / `{item['profile_id']}`"
            )
        lines.extend(["", "- Remote state kinds:"])
        lines.extend([f"  - {kind}" for kind in profile["remote_state_kinds"]])
        lines.extend(["", "- Hosting mutation record fields:"])
        lines.extend([f"  - {field}" for field in profile["mutation_record_fields"]])
        lines.extend(["", "- Deployment state:"])
        lines.extend(render_nested_value(profile["deployment_state"], 1))
        lines.append("")
    return lines


def render_field_sections(fields: list[dict]) -> list[str]:
    lines = ["## Canonical fields", ""]
    for field in fields:
        validation = field.get("validation")
        lines.extend(
            [
                f"### {field['label']}",
                "",
                f"- Field ID: `{field['id']}`",
                f"- Required: {'yes' if field['required'] else 'no'}",
                f"- Input type: `{field['input_type']}`",
                "",
                field["description"],
                "",
                "Placeholder:",
            ]
        )
        for line in field["placeholder"].splitlines() or [""]:
            lines.append(f"> {line}" if line else ">")
        if validation:
            lines.extend(["", "Validation metadata:", "", f"- Kind: `{validation['kind']}`"])
            if "branch" in validation:
                lines.append(f"- Branch: `{validation['branch']}`")
            if validation.get("allow_none"):
                lines.append("- Allows `None`: yes")
            if "count" in validation:
                lines.append(f"- Count: `{validation['count']}`")
            if validation.get("items"):
                lines.append("- Items:")
                lines.extend([f"  - {item}" for item in validation["items"]])
        lines.append("")
    return lines


def render_issue_form(spec: dict) -> str:
    lines = [
        "name: Governing issue",
        "description: Create a standardized governing issue for bounded governed work.",
        'title: "[governed] "',
        "labels:",
        "  - governed-work",
        "body:",
        "  - type: markdown",
        "    attributes:",
        "      value: |",
        "        Use this form to create the canonical governing issue. Required fields must be filled with substantive content; placeholders do not count as complete.",
    ]
    for field in spec["issue_fields"]:
        lines.extend(
            [
                f"  - type: {field['input_type']}",
                f"    id: {field['id']}",
                "    attributes:",
                f"      label: {json.dumps(field['label'])}",
                f"      description: {json.dumps(field['description'])}",
                f"      placeholder: {json.dumps(field['placeholder'])}",
                "    validations:",
                f"      required: {'true' if field['required'] else 'false'}",
            ]
        )
    return "\n".join(lines) + "\n"


def render_review_template(spec: dict) -> str:
    fields = spec["review_fields"]
    lines = [
        "<!-- Link the governing issue in GitHub's Development section. -->",
        "<!-- Do not use automatic close syntax unless the governing issue explicitly permits it. -->",
        "",
    ]
    for field in fields:
        comment = field.get("adapter_hint", field["description"])
        lines.extend([f"## {field['label']}", "", f"<!-- {comment} -->", ""])
    return "\n".join(lines)


def render_authoritative_specs(spec: dict) -> list[str]:
    return [f"- `{entry['spec_id']}` -> `{entry['path']}`" for entry in spec.get("authoritative_specs", [])]


def render_lineage(spec: dict) -> list[str]:
    lines: list[str] = []
    if spec.get("supersedes"):
        lines.append("## Supersedes")
        lines.append("")
        lines.extend([f"- `{spec_id}`" for spec_id in spec["supersedes"]])
        lines.append("")
    if spec.get("superseded_by"):
        lines.append("## Superseded By")
        lines.append("")
        lines.extend([f"- `{spec_id}`" for spec_id in spec["superseded_by"]])
        lines.append("")
    return lines


def render_spec_projection(title: str, source_path: str, spec: dict, include_authoritative_specs: bool = False) -> str:
    lines = [header(title, source_path), "## Purpose", "", spec["purpose"], ""]
    if "correspondence" in spec:
        lines.extend(render_correspondence(spec))
    if "artifact_classes" in spec:
        lines.extend(render_artifact_classes(spec))
    if "profiles" in spec:
        lines.extend(render_profiles(spec))
    if "issue_fields" in spec:
        lines.extend(render_field_sections(spec["issue_fields"]))
    elif "review_fields" in spec:
        lines.extend(render_field_sections(spec["review_fields"]))
    lines.extend(render_extra_sections(spec))
    lines.extend(render_lineage(spec))
    if include_authoritative_specs:
        lines.extend(render_list_section("Authoritative specs", render_authoritative_specs(spec)))
    lines.extend(render_list_section("Normative requirements", render_requirements(spec)))
    lines.extend(render_list_section("Dependencies", render_dependencies(spec)))
    lines.extend(render_list_section("References", render_references(spec)))
    lines.extend(render_list_section("Derived artifacts", render_derived_artifacts(spec)))
    return "\n".join(lines) + "\n"


SPECIAL_RENDERERS = {
    "issue-form": render_issue_form,
    "review-template": render_review_template,
}


def actual_derived_markdown_paths(repo_root: Path) -> set[str]:
    derived_root = repo_root / "product/derived/specs/product"
    if not derived_root.exists():
        return set()
    return {
        path.relative_to(repo_root).as_posix()
        for path in derived_root.rglob("*.md")
        if path.is_file()
    }


def check_orphaned_derived_markdown(repo_root: Path, expected_paths: set[str], strict: bool) -> None:
    actual_paths = actual_derived_markdown_paths(repo_root)
    missing = sorted(expected_paths - actual_paths)
    extra = sorted(actual_paths - expected_paths)
    if strict:
        if missing or extra:
            parts: list[str] = []
            if missing:
                parts.append(f"missing derived markdown: {', '.join(missing)}")
            if extra:
                parts.append(f"orphaned derived markdown: {', '.join(extra)}")
            raise ValueError("; ".join(parts))
        return
    if extra:
        raise ValueError(f"orphaned derived markdown: {', '.join(extra)}")


def render_all(repo_root: Path) -> dict[str, str]:
    detailed = render_all_detailed(repo_root)
    return {path: content for path, (_source_path, content) in detailed.items()}


def render_all_detailed(repo_root: Path) -> dict[str, tuple[str, str]]:
    _product_manifest, specs, paths, _actual_paths = load_product_specs(repo_root)
    rendered: dict[str, tuple[str, str]] = {}
    for spec_id in sorted(specs, key=lambda item: paths[item]):
        spec = specs[spec_id]
        source_path = paths[spec_id]
        for artifact in spec.get("derived_artifacts", []):
            resolve_repo_path(repo_root, artifact["path"])
            renderer_id = artifact.get("renderer")
            if renderer_id is None:
                if artifact["type"] != "markdown":
                    raise ValueError(f"unsupported derived artifact type without renderer: {artifact['type']}")
                rendered[artifact["path"]] = (
                    source_path,
                    render_spec_projection(
                    spec["title"],
                    source_path,
                    spec,
                    include_authoritative_specs=False,
                    ),
                )
                continue
            renderer = SPECIAL_RENDERERS.get(renderer_id)
            if renderer is None:
                raise ValueError(f"unsupported renderer: {renderer_id}")
            rendered[artifact["path"]] = (source_path, renderer(spec))
    declared_paths = declared_derived_artifact_paths(specs)
    if set(rendered) != declared_paths:
        raise ValueError("declared derived-artifacts do not match generated outputs")
    return rendered


def write_all(repo_root: Path) -> None:
    rendered = render_all_detailed(repo_root)
    for relative_path, (_source_path, content) in rendered.items():
        path = resolve_repo_path(repo_root, relative_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)


def check_generated_outputs(repo_root: Path) -> None:
    rendered = render_all_detailed(repo_root)
    expected_markdown_paths = {path for path in rendered if path.endswith(".md") and (path.startswith("product/derived/specs/"))}
    check_orphaned_derived_markdown(repo_root, expected_markdown_paths, strict=True)
    for relative_path, (source_path, content) in rendered.items():
        path = resolve_repo_path(repo_root, relative_path)
        if not path.exists() or path.read_text() != content:
            raise ValueError(f"stale generated document: source {source_path} -> output {path.relative_to(repo_root)}")


def main(argv: list[str]) -> int:
    repo_root = Path(argv[1]).resolve() if len(argv) > 1 else Path.cwd().resolve()
    mode = argv[2] if len(argv) > 2 else "--write"
    rendered = render_all_detailed(repo_root)
    expected_markdown_paths = {path for path in rendered if path.endswith(".md") and (path.startswith("product/derived/specs/"))}

    if mode == "--write":
        check_orphaned_derived_markdown(repo_root, expected_markdown_paths, strict=False)
        for relative_path, (_source_path, content) in rendered.items():
            path = resolve_repo_path(repo_root, relative_path)
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
        return 0

    if mode == "--check":
        check_orphaned_derived_markdown(repo_root, expected_markdown_paths, strict=True)
        for relative_path, (source_path, content) in rendered.items():
            path = resolve_repo_path(repo_root, relative_path)
            if not path.exists() or path.read_text() != content:
                print(f"stale generated document: source {source_path} -> output {path.relative_to(repo_root)}", file=sys.stderr)
                return 1
        return 0

    print(f"unknown mode: {mode}", file=sys.stderr)
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
